name: Build iOS IPA
on: [push]

jobs:
  build:
    name: Flutter iOS build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41'

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-ipa
          path: |
            build/ios/ipa/*.ipa
            build/ios/archive/*.xcarchive
            **/Runner.app
